#
# HTTP
#
host: 0.0.0.0
port: 80

#
# Relay mapping
#
relays:
  - id: 0
    chip: gpiochip1
    line: 1
    active: high
    default: 1

  - id: 1
    chip: gpiochip1
    line: 1
    active: low
    default: 0
